server:
  port: 18081
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    tags-sorter: alpha
    enabled: true

swagger:
  server:
    url: http://localhost:18081/api

logging:
  level:
    root: INFO
    com.javaTest: DEBUG
    org.springframework.web: WARN
    org.hibernate: ERROR

spring:
  application:
    name: backend-server
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/db
    username: root
    password: myPassword
#    hikari:
#      minimumIdle: 10
#      maximumPoolSize: 30
#      idleTimeout: 120000
#      connectionTimeout: 300000
#      leakDetectionThreshold: 300000
#      max-lifetime: 600000
#      auto-commit: true
#      connection-test-query: SELECT 1
#      transaction-isolation: TRANSACTION_READ_UNCOMMITTED

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
      naming:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      client:
        decode-slash: false
